"use strict";

// core/cli/command-list.js — the single map of command name -> command module
// name. bin/devteam and core/cli/commands/help.js (phase 37.1: generated
// per-command help) both resolve commands through this list, so a new command
// only needs to be registered in one place.
module.exports = Object.freeze({
  help: "help",
  stages: "stages",
  hosts: "hosts",
  doctor: "doctor",
  summary: "summary",
  log: "log",
  stage: "stage",
  preflight: "preflight",
  advise: "advise",
  next: "next",
  run: "run",
  commit: "commit",
  compact: "compact",
  validate: "validate",
  "verify-chain": "verify-chain",
  "stamp-chain": "stamp-chain",
  merge: "merge",
  "derive-approvals": "derive-approvals",
  restart: "restart",
  ruling: "ruling",
  "fix-escalation": "fix-escalation",
  init: "init",
  ui: "ui",
  memory: "memory",
  architecture: "architecture",
  reproduce: "reproduce",
  verify: "verify",
  replay: "replay",
  ci: "ci",
  spec: "spec",
  consistency: "consistency",
  assess: "assess",
  standards: "standards",
  hook: "hook",
  status: "status",
  evidence: "evidence",
  report: "report",
  prototype: "prototype",
  performance: "performance",
  patterns: "patterns",
  corpus: "corpus",
  evals: "evals",
  "review-pr": "review-pr",
  review: "review",
});
